In [1]:
from operator import mul
from math import factorial
from algo import *
import pandas as pd
import numpy as np

In [3]:
q = symbols('q')


expand(q**3*q_poly(q, 2)+ 3*q**2*q_poly(q, 4) + 3*q*q_poly(q, 6) + q_poly(q, 8))


q**7 + 4*q**6 + 7*q**5 + 8*q**4 + 8*q**3 + 7*q**2 + 4*q + 1

In [4]:

def ex_df(n, h):
    if type(h) == int:
        h=h_function(h, n)
    l = []
    for p in permutations(range(1,n+1)):
        P, Q = PRSK(p, h)
        l.append(( shape(P), P_inv(P, h), P, Q, reading_word(Q),h))
    return pd.DataFrame(
        l,
        columns=[
            'shapes',
            'inv',
            'P',
            'Q',
            'Q_word',
            'h'
        ]).sort_values(by=['inv']).sort_values(by='P').sort_values(by='Q')


In [6]:
df = ex_df(5, 2)

df

shapes  inv                      P                      Q  \
112  (2, 2, 1)    2  [[1, 2], [3, 4], [5]]  [[1, 2], [3, 4], [5]]   
94   (2, 2, 1)    2  [[1, 2], [3, 4], [5]]  [[1, 2], [3, 5], [4]]   
108  (3, 1, 1)    2  [[1, 2, 4], [3], [5]]  [[1, 2, 3], [4], [5]]   
66      (3, 2)    2    [[1, 2, 4], [3, 5]]    [[1, 2, 3], [4, 5]]   
62      (3, 2)    2    [[2, 1, 5], [4, 3]]    [[1, 2, 3], [4, 5]]   
..         ...  ...                    ...                    ...   
61      (3, 2)    1    [[1, 2, 5], [3, 4]]    [[1, 3, 5], [2, 4]]   
13      (3, 2)    1    [[1, 2, 3], [4, 5]]    [[1, 3, 5], [2, 4]]   
63      (3, 2)    2    [[2, 1, 5], [4, 3]]    [[1, 3, 5], [2, 4]]   
83   (2, 2, 1)    2  [[1, 2], [3, 4], [5]]  [[1, 4], [2, 5], [3]]   
41   (3, 1, 1)    2  [[1, 2, 4], [3], [5]]  [[1, 4, 5], [2], [3]]   

              Q_word                h  
112  [1, 2, 3, 4, 5]  [2, 3, 4, 5, 5]  
94   [1, 2, 3, 5, 4]  [2, 3, 4, 5, 5]  
108  [1, 2, 3, 4, 5]  [2, 3, 4, 5, 5]  
66   [1, 2, 3, 4, 5]  [2, 3, 4, 5, 5]  
62   [1, 2, 3, 4, 5]  [2, 3, 4, 5, 5]  
..               ...              ...  
61   [1, 3, 5, 2, 4]  [2, 3, 4, 5, 5]  
13   [1, 3, 5, 2, 4]  [2, 3, 4, 5, 5]  
63   [1, 3, 5, 2, 4]  [2, 3, 4, 5, 5]  
83   [1, 4, 2, 5, 3]  [2, 3, 4, 5, 5]  
41   [1, 4, 5, 2, 3]  [2, 3, 4, 5, 5]  

[120 rows x 6 columns]

In [7]:

n = 6
c = coef(4, 2)
c[2][(2,2)]

1

In [ ]:

q_fact('q', 4)
q_binom('q', 6,5)
perm_coefs(3, [1, 3, 3])

def permDF(n, h):
    c = [("".join([str(k)+"::" for k in p]))[:-2] for p in partitions(n)]
    df = pd.DataFrame(perm_coefs(n,h), columns=c)
    df.index.name = df.index = df.index.rename('degree')
    return df


permDF(3,[2,3,3])
permDF(3, [3,3,3])
[0,0,0], [1,1,1], [q,q,q]
permDF(4, [2,3,4,4])
permDF(4, [3,3,4,4])

df = permDF(n,h)


for n in range(3,8):
    h = list(range(n))
    for j in range(n):
        if j == 0:
            h[j] = min(2, n)
        if j == 1:
            h[j] = min(4, n)
        else:
            h[j] = min(j+3, n)
    check(n,h)

pd.read_csv("".join([str(k) for k in [3,3,4,4]])+".csv", sep=";")

"".join([str(i) for i in h])
p = [3,2,2]

def check(n, h):
    df = permDF(n,h)
    v = [factorial(n)/np.prod(np.array([factorial(i) for i in p])) for p in partitions(n)]
    print(sum(df@v) == factorial(n))
check(5, [2,4,4,5,5])


for p in permutations([1,2,3]):
    print(p, code(zero_d2e(p)), RSK(code(zero_d2e(p))[0]), PRSK(p[::-1], 2))


for p in permutations([1,2,3,4]):
    print(p, code(zero_d2e(p)), RSK(code(zero_d2e(p))[0]))


In [19]:
def K(n):
    coefs = {}
    inner = {tuple(q): 0 for q in partitions(n)}
    for p in partitions(n):
        coefs[tuple(p)] = inner.copy()
        # create a list of p_1 1's, p_2 2's, etc...
        seq = [[i + 1] * p[i] for i in range(len(p))]
        seq = [i for sub in seq for i in sub]
        
        q = []
        """
        this will die as n grows, but loop over perms of the content
        run the RSK alg to get a SSYT and add one for each time the
        standard reading word comes up
        """
        for perm in permutations(seq):
            if perm not in q:
                P, Q = RSK(perm)
                q.append(perm)
                if reading_word(Q) == list(range(1, n + 1)):
                    coefs[tuple(p)][shape(P)] += 1

    # turn the data into a martic
    coefs = [coefs[p][i] for p in list(coefs) for i in list(coefs[p])]
    coefs = np.array(coefs).reshape(len(inner), len(inner)).T
    return coefs

In [21]:
K(4)

array([[1, 1, 1, 1, 1],
       [0, 1, 1, 2, 3],
       [0, 0, 1, 1, 2],
       [0, 0, 0, 1, 3],
       [0, 0, 0, 0, 1]])

In [11]:
[3]*[1,3][1]

[3, 3, 3]

In [17]:
w.__mul__(w).word

array([1, 2, 0])

In [24]:
w.power(1)._matrix

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [27]:
np.linalg.matrix_power(w._matrix, 1)

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [57]:
descent_algo([4, 8, 6, 3, 1, 2, 5, 7])

[4, 8, 6, 3, 1, 2, 5, 7]
max descent: 3
pq: [3, 1, 2]
valleys: [1]
min valley: 1
des_v: []
climbs: []
no climbs: [3, 1, 2]
left-over: [4, 8, 6, 5, 7]
max descent: 2
pq: [6, 5]
valleys: []
no valleys: [6, 5]
left-over: [4, 8, 7]
max descent: 1
pq: [8, 7]
valleys: []
no valleys: [8, 7]
left-over: [4]


([1, 1, 1, 0, 2, 2, 3, 3], {1: 1, 2: 1, 3: 1})

In [257]:
n = 4
id = [i+1 for i in range(n)]
df = pd.DataFrame(
    data=[[
        ww,
        str(descent_algo(ww)[0]), 
        str(descent_algo(ww)[1])
        ] for ww in permutations(id)],
    columns=['perm','code', 'index'])

#df.drop_duplicates().shape

[1, 2, 3, 4]
[1, 2, 3, 4]
[1, 2, 4, 3]
in the middle: [4, 3]
at the start: [4, 3]
valleys: []
no valleys: [4, 3]
left-over: [1, 2]
[1, 2, 4, 3]
in the middle: [4, 3]
at the start: [4, 3]
valleys: []
no valleys: [4, 3]
left-over: [1, 2]
[1, 3, 2, 4]
at the end
in the middle: [3, 2]
at the start: [3, 2]
valleys: []
no valleys: [3, 2]
left-over: [1, 4]
[1, 3, 2, 4]
at the end
in the middle: [3, 2]
at the start: [3, 2]
valleys: []
no valleys: [3, 2]
left-over: [1, 4]
[1, 3, 4, 2]
in the middle: [4, 2]
at the start: [4, 2]
valleys: []
no valleys: [4, 2]
left-over: [1, 3]
[1, 3, 4, 2]
in the middle: [4, 2]
at the start: [4, 2]
valleys: []
no valleys: [4, 2]
left-over: [1, 3]
[1, 4, 2, 3]
in the middle: [4, 2, 3]
at the start: [4, 2, 3]
valleys: [1]
min valley: 1
des_v: [0]
climbs: []
no climbs: [4, 2, 3]
left-over: [1]
[1, 4, 2, 3]
in the middle: [4, 2, 3]
at the start: [4, 2, 3]
valleys: [1]
min valley: 1
des_v: [0]
climbs: []
no climbs: [4, 2, 3]
left-over: [1]
[1, 4, 3, 2]
in the middle: 

In [259]:
df.sort_values(by=['code', 'index'])

#df.iloc[:, 1:].drop_duplicates().shape

perm          code         index
0   [1, 2, 3, 4]  [0, 0, 0, 0]            {}
1   [1, 2, 4, 3]  [0, 0, 1, 1]        {1: 1}
3   [1, 3, 4, 2]  [0, 1, 0, 1]        {1: 1}
2   [1, 3, 2, 4]  [0, 1, 1, 0]        {1: 1}
4   [1, 4, 2, 3]  [0, 1, 1, 1]        {1: 1}
5   [1, 4, 3, 2]  [0, 1, 1, 1]        {1: 2}
21  [4, 2, 3, 1]  [0, 1, 1, 1]        {1: 2}
9   [2, 3, 4, 1]  [1, 0, 0, 1]        {1: 1}
8   [2, 3, 1, 4]  [1, 0, 1, 0]        {1: 1}
10  [2, 4, 1, 3]  [1, 0, 1, 1]        {1: 1}
11  [2, 4, 3, 1]  [1, 0, 1, 1]        {1: 2}
19  [4, 1, 3, 2]  [1, 0, 1, 1]        {1: 2}
6   [2, 1, 3, 4]  [1, 1, 0, 0]        {1: 1}
16  [3, 4, 1, 2]  [1, 1, 0, 1]        {1: 1}
17  [3, 4, 2, 1]  [1, 1, 0, 1]        {1: 2}
12  [3, 1, 2, 4]  [1, 1, 1, 0]        {1: 1}
14  [3, 2, 1, 4]  [1, 1, 1, 0]        {1: 2}
18  [4, 1, 2, 3]  [1, 1, 1, 1]        {1: 1}
20  [4, 2, 1, 3]  [1, 1, 1, 1]        {1: 2}
22  [4, 3, 1, 2]  [1, 1, 1, 1]        {1: 2}
23  [4, 3, 2, 1]  [1, 1, 1, 1]        {1: 3}
15  [3, 2, 4, 1]  [1, 2, 2, 1]  {1: 2, 2: 1}
13  [3, 1, 4, 2]  [2, 1, 2, 1]  {1: 2, 2: 1}
7   [2, 1, 4, 3]  [2, 2, 1, 1]  {1: 2, 2: 1}

In [255]:
8*7*6*120

40320

In [256]:

def max_descent(p):
    return max([p[i] for i in descents(p)])


def index_max_descent(p):
    return p.index(max_descent(p))


def find_valleys(p):
    return [i for i in range(1, len(p) - 1) if p[i - 1] > p[i] < p[i + 1]]

def remover(pp):
    if pp == []:
        print('empty')
        return pp
    else: 
        N = pp.index(max(pp))
    if N == len(pp) - 1:
        print('at the end')
        return remover(pp[:-1])
    elif N > 0:
        print(f'in the middle: {pp[N:]}')
        return remover(pp[N:])
    else: # the max is at the begninning
        print(f'at the start: {pp}')
        valleys = find_valleys(pp)  # find the valleys in the substring
        print(f'valleys: {valleys}')
        if len(valleys) == 0:  # return the substring if no valleys
            print(f'no valleys: {pp}')
            return pp
        else:
            v = min(valleys)  # pick the first valley
            print(f'min valley: {v}')
            des_v = descents(pp[v:])  # look at the descents after the first valley
            print(f'des_v: {des_v}')
            if des_v != []:  # if no descents then recurse
                print(f'recurse: {pp[v:]}')
                return remover(pp[v:])
            else:
                climbs = [j for j in pp[v:] if (bisect(pp[v - 1::-1], j) != 0)] # note we are looking in reverse
                print(f'climbs: {climbs}')
                if climbs == []:
                    print(f'no climbs: {pp}')
                    return pp
                else:
                    j = min(climbs)
                    print(f'min climb: {[i for i in pp if (i < j)]}')
                    return [i for i in pp if (i < j)]
            

def remove(p, q):
    return [i for i in p if i not in q]


def sequence(a, p, i):
    for j in p:
        a[j - 1] = i
    return a


def descent_algo(p):
    print(p)
    pp = p
    i = 0
    a = [0 for i in sorted(p)]
    deg = {i: 0 for i in range(2 * len(p))}
    while pp != sorted(pp):
        pq = remover(pp)
        d = desc(pp)
        i += 1
        deg[i] = d
        pp = remove(pp, pq)
        print(f'left-over: {pp}')
        a = sequence(a, pq, i)
    deg = {i: deg[i] for i in deg.keys() if deg[i] != 0}
    return a, deg

In [261]:
descents([3,2,4,1])

[0, 2]

In [83]:
l = [1,2,6,4,5,3]

N = l.index(max(l))

l[:N]


l[N:]


[6, 4, 5, 3]

# OLD VERSIONS

In [ ]:

def max_descent(p):
    return max([p[i] for i in descents(p)])


def index_max_descent(p):
    return p.index(max_descent(p))


def find_valleys(p):
    return [i for i in range(1, len(p) - 1) if p[i - 1] > p[i] < p[i + 1]]

def remover(pp):
    mn = index_max_descent(pp)  # location of max descent
    m = max_descent(pp)  # value of max descent
    try:
        M = min([j for j in pp[mn:] if j > m])  # value of lowest value greater than max descent
        MN = pp.index(M)  # location of above
    except:
        MN = len(pp)  # last value if nothing is bigger than max descent
    pq = pp[mn:MN]  # substring between max descent and smallest value bigger than max descent
    print(f'max descent: {m}')
    print(f'pq: {pq}')
    valleys = find_valleys(pq)  # find the valleys in the substring
    print(f'valleys: {valleys}')
    if len(valleys) == 0:  # return the substring if no valleys
        print(f'no valleys: {pq}')
        return pq
    else:
        v = min(valleys)  # pick the first valley
        print(f'min valley: {v}')
        des_v = descents(pq[v:])  # look at the descents after the first valley
        print(f'des_v: {des_v}')
        if des_v != []:  # if no descents then recurse
            print(f'recurse: {pq[v:]}')
            return remover(pq[v:])
        else:
            climbs = [j for j in pq[v:] if (bisect(pq[v - 1::-1], j) != 0)] # note we are looking in reverse
            print(f'climbs: {climbs}')
            if climbs == []:
                print(f'no climbs: {pq}')
                return pq
            else:
                j = min(climbs)
                print(f'min climb: {[i for i in pq if (i < j)]}')
                return [i for i in pq if (i < j)]


def remove(p, q):
    return [i for i in p if i not in q]


def sequence(a, p, i):
    for j in p:
        a[j - 1] = i
    return a


def descent_algo(p):
    print(p)
    pp = p
    i = 0
    a = [0 for i in sorted(p)]
    deg = {i: 0 for i in range(2 * len(p))}
    while pp != sorted(pp):
        pq = remover(pp)
        d = desc(pq)
        i += 1
        deg[i] = d
        pp = remove(pp, pq)
        print(f'left-over: {pp}')
        a = sequence(a, pq, i)
    deg = {i: deg[i] for i in deg.keys() if deg[i] != 0}
    return a, deg


# THESE DON'T WORK!

In [67]:


# index of max descent instead of max w_i that is a descent
#fails for n = 3


def max_descent(p):
    return max([i for i in descents(p)])


def index_max_descent(p):
    return p.index(max_descent(p))


def find_valleys(p):
    return [i for i in range(1, len(p) - 1) if p[i - 1] > p[i] < p[i + 1]]

def remover(pp):
    #mn = index_max_descent(pp)  # location of max descent
    m = max_descent(pp)  # value of max descent
    try:
        M = min([j for j in pp[m:] if j > pp[m]])  # value of lowest value greater than max descent
        MN = pp.index(M)  # location of above
    except:
        MN = len(pp)  # last value if nothing is bigger than max descent
    pq = pp[m:MN]  # substring between max descent and smallest value bigger than max descent
    print(f'max descent: {m}')
    print(f'pq: {pq}')
    valleys = find_valleys(pq)  # find the valleys in the substring
    print(f'valleys: {valleys}')
    if len(valleys) == 0:  # return the substring if no valleys
        print(f'no valleys: {pq}')
        return pq
    else:
        v = min(valleys)  # pick the first valley
        print(f'min valley: {v}')
        des_v = descents(pq[v:])  # look at the descents after the first valley
        print(f'des_v: {des_v}')
        if des_v != []:  # if no descents then recurse
            print(f'recurse: {pq[v:]}')
            return remover(pq[v:])
        else:
            climbs = [j for j in pq[v:] if bisect(pq[v - 1::-1], j) != 0] # note we are looking in reverse
            print(f'climbs: {climbs}')
            if climbs == []:
                print(f'no climbs: {pq}')
                return pq
            else:
                j = min(climbs)
                print(f'min climb: {[i for i in pq if (i < j)]}')
                return [i for i in pq if (i < j)]


def remove(p, q):
    return [i for i in p if i not in q]


def sequence(a, p, i):
    for j in p:
        a[j - 1] = i
    return a


def descent_algo(p):
    print(p)
    pp = p
    i = 0
    a = [0 for i in sorted(p)]
    deg = {i: 0 for i in range(2 * len(p))}
    while pp != sorted(pp):
        pq = remover(pp)
        d = desc(pq)
        i += 1
        deg[i] = d
        pp = remove(pp, pq)
        print(f'left-over: {pp}')
        a = sequence(a, pq, i)
    deg = {i: deg[i] for i in deg.keys() if deg[i] != 0}
    return a, deg


In [69]:

#infinite loop


def max_descent(p):
    return max([i for i in descents(p)])


def index_max_descent(p):
    return p.index(max_descent(p))


def find_valleys(p):
    return [i for i in range(1, len(p) - 1) if p[i - 1] > p[i] < p[i + 1]]

def remover(pp):
    #mn = index_max_descent(pp)  # location of max descent
    m = max_descent(pp)  # value of max descent
    try:
        M = min([j for j in pp[m:] if j > pp[m]])  # value of lowest value greater than max descent
        MN = pp.index(M)  # location of above
    except:
        MN = len(pp)  # last value if nothing is bigger than max descent
    pq = pp[m:MN]  # substring between max descent and smallest value bigger than max descent
    print(f'max descent: {m}')
    print(f'pq: {pq}')
    valleys = find_valleys(pq)  # find the valleys in the substring
    print(f'valleys: {valleys}')
    if len(valleys) == 0:  # return the substring if no valleys
        print(f'no valleys: {pq}')
        return pq
    else:
        v = min(valleys)  # pick the first valley
        print(f'min valley: {v}')
        des_v = descents(pq[v:])  # look at the descents after the first valley
        print(f'des_v: {des_v}')
        if des_v != []:  # if no descents then recurse
            print(f'recurse: {pq[v:]}')
            return remover(pq[v:])
        else:
            climbs = [j for j in pq if bisect(pq[1::-1], j) != 0] # note we are looking in reverse
            print(f'climbs: {climbs}')
            if climbs == []:
                print(f'no climbs: {pq}')
                return pq
            else:
                j = min(climbs)
                print(f'min climb: {[i for i in pq if (i < j)]}')
                return [i for i in pq if (i < j)]


def remove(p, q):
    return [i for i in p if i not in q]


def sequence(a, p, i):
    for j in p:
        a[j - 1] = i
    return a


def descent_algo(p):
    print(p)
    pp = p
    i = 0
    a = [0 for i in sorted(p)]
    deg = {i: 0 for i in range(2 * len(p))}
    while pp != sorted(pp):
        pq = remover(pp)
        d = desc(pq)
        i += 1
        deg[i] = d
        pp = remove(pp, pq)
        print(f'left-over: {pp}')
        a = sequence(a, pq, i)
    deg = {i: deg[i] for i in deg.keys() if deg[i] != 0}
    return a, deg
